### PR TITLE
(GH-379) Add sync lock on send mail to avoid async issues

### PR DESCRIPTION
**Pull request by Thilas**
I use a basic lock to make sure we don't try to simultaneously send mail on different threads and on the same SmtpClient instance.

Since emails need to be sent synchronously (according to what I saw in the code), it makes more sense to do fix this issue this way instead of using the ThreadPool (eg http://stackoverflow.com/a/16438292/18475) or Task (like I suggested).

Otherwise, an other solution would be to instantiate SmtpClient each time we need it instead of using the current singleton.

### CODE REVIEW

**Comment by ferventcoder** [comment]
I'd like a Monitor with a timeout, otherwise this could be waiting for a long period of time. Thoughts?

**Comment by Thilas** [comment]
Good idea. I set a timeout of 1 sec. Do you think it's ok?

**Comment by ferventcoder** [comment]
Maybe give it about 5 seconds.

**Comment by Thilas** [comment]
Done.

**Comment by Thilas** [comment]
@ferventcoder, is there anything I can do on this PR in order to get it merged? Thanks.

**Comment by Thilas** [comment]
Fixes #379.

@ferventcoder, I just noticed this PR was still open. Aren't you interested in merging it?

**Comment by gep13** [comment]
@Thilas your changes have been merged, thanks for your contribution 👍

**Pull request merged**
