### PR TITLE
Changed Comment Post Url

### PR DESCRIPTION
**Pull request by gep13**
- Changed default value of ForceSSL to be false (so that it will work
locally)
- Updated notes above Disqus thread to indicate new notifications
- Following discussion with Rob, built up comment Post Url in a way that
it will hopefully work locally, and on staging and production

### CODE REVIEW

**Comment by gep13** [comment]
@ferventcoder ok, I "think" that this covers everything that we discussed.

Thoughts?

**Comment by gep13** [comment]
@ferventcoder ok, I "think" we are good to go now.

Final email looks like the following:

image

**Comment by ferventcoder** [comment]
That is beautiful.

**Comment by gep13** [comment]
@ferventcoder when are you planning on pulling the trigger on this and pushing to chocolatey.org? Thanks!

**Comment by ferventcoder** [comment]
Done.

**Pull request merged**
