### PR TITLE
(GH-728) Reinstate lost moderation permissions

### LINKED ISSUE #728: Some package permissions lost with redesign
With the redesign, some of the package permissions of moderators and maintainers has been lost. This includes access to moderate unrejected packages. This is likely caused by improper nesting of razor syntax in the DisplayPackage.cshmtl file.

### PR DESCRIPTION
**Pull request by designxsteph**
With the new redesign, some permissions of maintainers and
moderaters were lost. After comparing the DisplayPackage.cshmtl now to
how it was before the redesign, a few changes have been made to the
layout to ensure these permissions were reinstated. The overall
look/feel remains the same.

Fixes #728

### CODE REVIEW

**Comment by ferventcoder** [comment]
This has a merge conflict as well - and let's make sure there is an issue created that this is resolving.

**Comment by pauby** [comment]
I was able to change a package from Approved to Rejected, Submitted, Approved and between each status. So looks like it is working to me.

**Comment by designxsteph** [comment]
@pauby @gep13 @ferventcoder This branch has seemed to checkout with everyone that has tested it. Anything else that needs done on this one?

**Comment by gep13** [comment]
@designxsteph I have used this just now to unreject three packages that were sitting in my queue, and it all seems to be working as expected :+1:

**Pull request merged**
