### PR TITLE
Fix invalid PackagesController.generated.cs link.

### PR DESCRIPTION
**Pull request by DanAtkinson**

### CODE REVIEW

**Comment by DanAtkinson** [comment]
On my local version, I re-ran T4MVC and it picked up the RssController. I'm unable to submit a pull request locally at the moment, or I'd do it that way and include the missing RssController.generated.cs file..

**Comment by ferventcoder** [comment]
Can you explain the value of what this fixes?

**Comment by DanAtkinson** [comment]
Hi. Yes. When I open the solution in VS, I receive the following error:

image

In the solution explorer, `PackagesController.generated.cs` appears independently of T4MVC.tt, which it should be a child of.

If you attempt to run T4MVC, you get will also get the error above in that it's trying to create the `PackagesController.generated.cs` file but it already exists.

Thanks, Dan

**Comment by ferventcoder** [comment]
I bet if I installed T4MVC I'd also see this issue. Hmmmm

**Comment by gep13** [comment]
@ferventcoder I can confirm that I also see this issue when editing/debugging the chocolatey.org source code.  I normally workaround it, and simply never check-in the files that are touched as part of running the T4 templates.

**Comment by ferventcoder** [comment]
Yeah, this is not really going to fly. I'm going to move the T4MVC template over to the chocolatey side so it picks up the right files.

**Comment by ferventcoder** [comment]
Closing this in favor of the fixes I'm pushing up. 

For the future, fix/change nothing in nugetgallery folder. Anything that needs changes must first be copied over to chocolatey/Website folder. Apologies I didn't mention this previously. I did add the blurb in https://github.com/chocolatey/chocolatey.org/commit/9437de9be1eb7761367afc17aa01d19c537f9df9

**Comment by ferventcoder** [comment]
The fixes were https://github.com/chocolatey/chocolatey.org/commit/d2d8065d513a01920cff48ef87bbd5ceb2668d16 and https://github.com/chocolatey/chocolatey.org/commit/ab52cbafc7d9b934292680192e1f1eb38592720e

**Comment by DanAtkinson** [comment]
Thanks!

**Pull request closed without merging**
