### PR TITLE
(events) Add Ansible + Chocolatey Webinar Page

### PR DESCRIPTION
**Pull request by designxsteph**
Adds a new event for the Ansible + Chocolatey webinar that takes place
on December 10, 2020.

### CODE REVIEW

**Comment by designxsteph** [comment]
@ferventcoder This is up on test.

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@designxsteph thanks for getting this added.  I will get this deployed to chocolatey.org just now.

**Comment by gep13** [comment]
@designxsteph this is now live.

**Pull request merged**
