### PR TITLE
(GH-543) Fixes the non-clickable menu in the old site layout

### LINKED ISSUE #543: Search box expansion does not allow clicking on links when it is NOT expanded
FYI @derickbailey 
image

I'm going to see what can be done, but may need to roll this back for now.

### PR DESCRIPTION
**Pull request by derickbailey**
this correct to the css for the expanding layout on the old site design allows the menus to be clickable when the search box is not expanded

Fixes #543

### CODE REVIEW

**Comment by derickbailey** [comment]
fixes #543

**Comment by ferventcoder** [comment]
https://github.com/chocolatey/chocolatey.org/commit/1204933948e089c6a72f48ef0c80807501ca43ef is another good example of this.

**Comment by ferventcoder** [comment]
I can also do this

**Comment by ferventcoder** [comment]
I've made the adjustments so we can get this pushed.

**Comment by ferventcoder** [comment]
Merged in at https://github.com/chocolatey/chocolatey.org/commit/ef553b5f7dd2ca10fa22b3db881760ec89c1d0b8

**Pull request closed without merging**
