### PR TITLE
(layout) Add New Offline Deployments Solution Page

### PR DESCRIPTION
**Pull request by designxsteph**
In this PR: 

* Adds a new Secure Offline Deployments page

### CODE REVIEW

**Comment by designxsteph** [comment]
This is on test under the solutions top navigation. There are still content updates to be made. @ferventcoder

**Comment by designxsteph** [comment]
@ferventcoder This is up on test and is ready to go. This adds only the Secure Offline Deployments page.

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
Had a chat with @ferventcoder and he mentioned that he was happy with this, so going to go ahead and merge this in.

**Comment by gep13** [comment]
@designxsteph thanks for getting this added, this should now be live on the site.

**Pull request merged**
