### PR TITLE
Advise Maintainers to post to Disqus

### PR DESCRIPTION
**Pull request by gep13**
- This is a fixed up pull request for the work that @redsandro did in
GH-92
- A rebase was required that he wasn't comfortable doing, so this will
replace his PR

### CODE REVIEW

**Comment by Redsandro** [comment]
Thank you. :+1:

**Comment by ferventcoder** [comment]
Closes #92

**Comment by Redsandro** [comment]
I see this is in. But the link is not working for me. It takes me to the package page, but not to the disqus anchor. Anyone else have this? Tested on Chromium 39 / Ubuntu. If not, nevermind.

---

If so, I don't know why this is. It is as if the anchor doesn't register in this particular website. Is it dynamically added to the body later? If so, it doesn't work.

One workaround would be to have `location.hash='disqus'` on the `onLoad` event, or after the content is added if it happens dynamically. Of course, anchor names only work when they change, so we would have to come from something arbitrary, e.g.

```
onLoad() {
  if (location.hash=='disqus') {
    location.hash='disqusanchor';
    location.hash='disqus';
  }
}
```

Just a thought. There are probably better fixes.

**Comment by gep13** [comment]
@Redsandro can you provide an example of the generated URL?

**Comment by Redsandro** [comment]
https://chocolatey.org/packages/chocolatey#disqus

**Comment by gep13** [comment]
Ah, I see what you mean.  The URL doesn't work until the disqus object is loaded on the page, which doesn't happen until you scroll down to the bottom.  This will need some work.

**Comment by ferventcoder** [comment]
The anchor is actually there. It's something with all anchors - not just this one

**Comment by ferventcoder** [comment]
Although that link worked for me, I see Chrome go back and forth on working properly with anchors.

**Pull request merged**
