### PR TITLE
updated the package listing page layout and styles

### PR DESCRIPTION
**Pull request by derickbailey**
this PR updates the package listing page to use the new site design, and adjusts many of the existing styles for the package list, including that of the moderator view, etc. 

additional changes were made in the overall site search to match the new styles as well

### CODE REVIEW

**Comment by ferventcoder** [comment]
At a high level review of just reading the code, it looks awesome. Let's see how it looks when running the code. 👍

**Comment by gep13** [comment]
@derickbailey could you grab a couple screenshots, not in a position to run up the site just now.

**Comment by derickbailey** [comment]
@gep13 yeah - here are a few screen shots 

when not logged in:

image

when logged in:

image

responsive css for mobile sizes:

image

moderator view

image

**Comment by gep13** [comment]
@derickbailey nice! Looks good to me :-)

One question...

Do we still want/need the blue banner colour across the top of the screen when in mobile view?

**Comment by ferventcoder** [comment]
@gep13 that's an already existing design in mobile, so...

**Comment by ferventcoder** [comment]
Going to close this one as stale - we ended up going a different direction. This was some fantastic work though!

**Pull request closed without merging**
