### PR TITLE
Add 12 Days of Chocolatey videos to resources

### PR DESCRIPTION
**Pull request by designxsteph**
In this PR:

* Adds the 12 Days of Chocolatey videos to the resource area
* Updates the event page with these videos instead of directly to YouTube

### CODE REVIEW

**Comment by designxsteph** [comment]
This is on test.

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@designxsteph thanks for getting this updated.

Going to get this pushed out just now.

**Comment by gep13** [comment]
@designxsteph this should now be live on the site.

**Pull request merged**
