### PR TITLE
fixed a link for "Running Chocolatey on Linux"

### PR DESCRIPTION
**Pull request by kishkin**
Hello!

Just fixed a broken link.

Thank you for chocolatey!

### CODE REVIEW

**Comment by ferventcoder** [comment]
I'm not sure if you saw the readme - this comes in from htttps://github.com/chocolatey/choco-wiki. Can you make this fix over there?

**Comment by kishkin** [comment]
Sure. Sorry for messing up. Hope I did it right this time.

**Comment by ferventcoder** [comment]
No worries - folks miss that readme quite a bit.

**Comment by ferventcoder** [comment]
https://github.com/chocolatey/choco-wiki/pull/65

**Pull request closed without merging**
