### PR TITLE
Advise maintainers to answer questions publicly on Disqus.

### PR DESCRIPTION
**Pull request by Redsandro**
Whenever someone contacts package maintainers with a question, include a link to the package comment section:

> User xyz sends the following message to the maintainers of Package 'abc'.
> 
> ...
> 
> Package Url: http://chocolatey.org/packages/abc
> 
> __Pro-tip:__ It is recommended to (also) post your answer to [the abc comment section](http://chocolatey.org/packages/abc#disqus) so that the information is publicly available. This can prevent you from receiving the same question from multiple users.
> 
> Package comments: [http://chocolatey.org/packages/abc#disqus](http://chocolatey.org/packages/abc#disqus)
> 
> ---
> To stop receiving contact emails as a maintainer of this package, sign in to the Chocolatey Gallery and change your email notification settings.

### CODE REVIEW

**Comment by ferventcoder** [comment]
I thought I already put the code in for this...

**Comment by Redsandro** [comment]
Haven't seen it yet.

**Comment by gep13** [comment]
@Redsandro so I am confused... (yes, easily done :smile_cat: )

What exactly are you asking for here?  What is missing, and what needs to be added where?

As part of this pull request, you have added:

```<a name="disqus"></a>```

to the DisplayPackage.cshtml page.  Does this need to be somewhere else as well?

**Comment by Redsandro** [comment]
@gep13 I don't know what code @ferventcoder (already) added, but the `<a name="disqus"></a>` code needs to be right above the `disqus_thread`. This is a named anchor, AKA a bookmark inside a package page on the gallery. This named anchor will scroll the page directly to the `disqus_thread` div. This is necessary, otherwise the links in the email template will not work:

```
<b>Pro-tip:</b> It is recommended to (also) post your answer to [the {2} comment section](http://chocolatey.org/packages/{2}#disqus) so that the information is publicly available.
This can prevent you from receiving the same question from multiple users.

Package comments: [http://chocolatey.org/packages/{2}#disqus](http://chocolatey.org/packages/{2}#disqus)
```

(note the `#disqus`)

**Comment by gep13** [comment]
@Redsandro so again, in the commit, that you added, associated with this pull request, this anchor tag exists:

https://github.com/chocolatey/chocolatey.org/pull/92/files#diff-93719c9ea6a754588333cb97093ed3e3R258

Right?  Or am I missing something?  So, assuming that this Pull Request gets accepted, everything will be as required, right?

**Comment by Redsandro** [comment]
In theory, yes, but..

1. I don't have the resources (IIS/Windows) and/or knowhow to test this change out.
1. I made two small changes but I see big areas of red and green even though the actual lines seem identical, so maybe my edits on Linux changed something irrelevant (again).
1. This pull request is so old that merge conflicts have emerged by now.

I think someone should add this manually. It' s indeed the lines @ferventcoder mentioned on Oct 31 plus the anchor that is already in the pull request.

Yes, in theory this should work.

**Comment by gep13** [comment]
Ok, are we all in agreement: https://github.com/chocolatey/chocolatey.org/pull/145

**Pull request closed without merging**
