### PR TITLE
Fix docs typo (minor)

### PR DESCRIPTION
**Pull request by darthwalsh**
Its not It's.

### CODE REVIEW

**Comment by ferventcoder** [comment]
Thank you. I'm not sure if we have a note in the documetation view folder but for fixes to this, you need to aubmit that to https://github.com/chocolatey/choco-wiki. HTH

**Comment by ferventcoder** [comment]
I will work on adding a readme type file to the very top of this folder

**Comment by darthwalsh** [comment]
Maybe you can delete this documentation folder? Less duplication means less mistakes :D

**Comment by ferventcoder** [comment]
The docs here are the output of a process that converts the markdown to cshtml. Hopefully we can eradicate most of that, but this was the first pass to dot org becoming the one stop for docs, info, and the community packages.

**Pull request closed without merging**
