### PR TITLE
(layout) Add Webinar Announcement to Home Page

### PR DESCRIPTION
**Pull request by designxsteph**
Updates the blue announcement section on the home page from Covid-19
updates to information about the upcoming webinar "Enable Your Remote
Workforce by Implementing Modern Infrastructure with Chocolatey".

### CODE REVIEW

**Comment by designxsteph** [comment]
@ferventcoder @gep13 This is up on test

**Comment by gep13** [comment]
@designxsteph this looks really good to me.  If we get a final nod from @ferventcoder I can get this pulled in, and pushed out to chocolatey.org.

**Comment by ferventcoder** [comment]
👍

**Comment by gep13** [comment]
@designxsteph this has been approved by @ferventcoder so going to go ahead and get this merged in.

**Comment by gep13** [comment]
@designxsteph this is now live on the site.  Thanks for getting this done! :+1:

**Pull request merged**
