### PR TITLE
(GH-897) Fully Qualified Expand-Archive

### PR DESCRIPTION
**Pull request by joshcorr**
This is a proposed change for #897

Please reach out if you have any questions about this issue.

### CODE REVIEW

**Comment by gep13** [comment]
@vexx32 @steviecoaster @pauby any thoughts/concerns on this change?

**Comment by gep13** [comment]
**NOTE:** If this PR is merged, it will need the signature block to be updated.

**Comment by vexx32** [comment]
Makes sense to do, I think, if only because the pscx module was pretty popular for a while and may still persist in some environments.

Seems like a good change to me. :+1:

**Comment by joshcorr** [comment]
This may need to be added to other scripts or documentation locations like [this one](https://chocolatey.org/docs/installation#completely-offline-install). I originally found the problem when installing from a local nuget repo.

**Comment by joshcorr** [comment]
@ferventcoder @gep13 @vexx32 Did this PR need to get pulled in? Or Closed since #912 was doing a similar thing?

**Comment by vexx32** [comment]
@joshcorr closing this for now as I've incorporated it into the more extensive changes in #912. Apologies for the long wait here, we'll get it sorted soon though 😁 

Thanks for your work here!

**Pull request closed without merging**
