### PR TITLE
(events) Add Multi Event Support for Countdown

### PR DESCRIPTION
**Pull request by designxsteph**
Adds support for multi event to the countdown timer. If there is more
than 1 event date listed, the timer will automatically lapse over
to the next available time until each time has past. When there are no
more times, then the timer will be removed like how it currently is.

### CODE REVIEW

**Comment by designxsteph** [comment]
@gep13 This will need to be merged before December 1st (the fist event of the 12 Days of Chocoaltey), or else the countdown timers/page will not function correctly. 

Also the Script.js may need to be purged in cloudflare for these changes to be updated. Usually its something like `/cassette.axd/script/5c021a518ec55854bd69b2e9a46b96868f6f9856/Scripts`

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@designxsteph I will go and get this deployed just now...

**Comment by designxsteph** [comment]
Thanks a bunch!

**Comment by gep13** [comment]
@designxsteph this has been deployed, and I believe I have purged everything that would need to be purged, can you have a look, and let me know if you are happy with it?

**Comment by designxsteph** [comment]
@gep13 Sorry about that, there is an additional PR here https://github.com/chocolatey/chocolatey.org/pull/1017 to make the countdown timer appear on the 12 Days and Ansible page. A needed class was reset accidentally after testing the timers.

**Pull request merged**
