### PR TITLE
(events) Update CSS for Countdown Timer

### PR DESCRIPTION
**Pull request by designxsteph**
Updates a css class that is needed to configure the countdown timer on
an events page. This also adds the new countdown markup to the Ansible
Webinar page so that the timer works correctly.

### CODE REVIEW

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@designxsteph I will let you know when this is deployed...

**Comment by designxsteph** [comment]
Thanks!

**Comment by gep13** [comment]
@designxsteph this should now be live.

**Comment by designxsteph** [comment]
Timers are working now!

**Comment by gep13** [comment]
Woot!  I will be signing off here in a little bit, but send me a message on Slack if you need anything over the weekend.

**Pull request merged**
