### PR TITLE
Ensure feedburner subscribe posts to a secure page

### PR DESCRIPTION
**Pull request by DanAtkinson**
Ensure feedburner subscribe posts to a secure page

### CODE REVIEW

**Comment by DanAtkinson** [comment]
Partially fixes #172.

**Comment by ferventcoder** [comment]
What are all of the other changes here?

**Comment by DanAtkinson** [comment]
That's a good question! I manually edited the single file in the webpage so my guess is that it perhaps changed the whitespace to make it unified. Was it mixed before?

Doing a [spilt diff](https://github.com/chocolatey/chocolatey.org/pull/174/files?diff=split) doesn't identify any other change, but for all intents and purposes, the http -> https change was the only one made.

Given that the file changes aren't immediately clear, my recommendation would be to reject this pull request and make the change manually yourself. :)

**Comment by ferventcoder** [comment]
This is a duplicate of #167

**Pull request closed without merging**
